name: MacTLA
options:
  bundleIdPrefix: com.tlaplus
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  SWIFT_VERSION: "5.9"
  MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  MacTLA:
    type: application
    platform: macOS
    sources:
      - path: TLAiPad
        excludes:
          - "**/*.xcassets"
      - path: TLAiPad/Assets.xcassets
    settings:
      INFOPLIST_GENERATION_MODE: GeneratedFile
      PRODUCT_BUNDLE_IDENTIFIER: com.tlaplus.MacTLA
      PRODUCT_NAME: "$(TARGET_NAME)"
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_STYLE: Automatic
      CODE_SIGN_IDENTITY: "-"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      ENABLE_PREVIEWS: YES
      SWIFT_EMIT_LOC_STRINGS: YES
      COMBINE_HIDPI_IMAGES: YES
      ENABLE_HARDENED_RUNTIME: YES
    info:
      path: TLAiPad/Info.plist
      properties:
        CFBundleDocumentTypes:
          - CFBundleTypeName: TLA+ Specification
            CFBundleTypeRole: Editor
            LSHandlerRank: Owner
            LSItemContentTypes:
              - com.tlaplus.specification
            NSDocumentClass: $(PRODUCT_MODULE_NAME).TLADocument
          - CFBundleTypeName: TLA+ Configuration
            CFBundleTypeRole: Editor
            LSHandlerRank: Owner
            LSItemContentTypes:
              - com.tlaplus.configuration
        UTExportedTypeDeclarations:
          - UTTypeConformsTo:
              - public.plain-text
            UTTypeDescription: TLA+ Specification
            UTTypeIdentifier: com.tlaplus.specification
            UTTypeTagSpecification:
              public.filename-extension:
                - tla
          - UTTypeConformsTo:
              - public.plain-text
            UTTypeDescription: TLA+ Configuration
            UTTypeIdentifier: com.tlaplus.configuration
            UTTypeTagSpecification:
              public.filename-extension:
                - cfg
        NSPrincipalClass: NSApplication
        LSMinimumSystemVersion: "14.0"

  MacTLATests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: TLAiPadTests
    dependencies:
      - target: MacTLA
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.tlaplus.MacTLATests
      PRODUCT_NAME: "$(TARGET_NAME)"
      CODE_SIGN_STYLE: Automatic
      GENERATE_INFOPLIST_FILE: YES

schemes:
  MacTLA:
    build:
      targets:
        MacTLA: all
        MacTLATests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - MacTLATests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
